[package]
name = "golf_geom"
description = "Analytic and NURBS curves and surfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
golf_manifold.workspace = true
golf_nurbs.workspace = true
nalgebra.workspace = true

[dev-dependencies]
golf_frame.workspace = true

[lints]
workspace = true
