[package]
name = "golf_brep"
description = "Boundary representation topology"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["mesh"]
# Implements golf_mesh::MeshSource for Body.
mesh = ["dep:golf_mesh"]

[dependencies]
golf_color.workspace = true
golf_geom.workspace = true
golf_mesh = { workspace = true, optional = true }
golf_manifold.workspace = true
nalgebra.workspace = true
thiserror.workspace = true

[dev-dependencies]
golf_frame.workspace = true

[lints]
workspace = true
