[package]
name = "golf_nurbs"
description = "NURBS curves and surfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
nalgebra.workspace = true
thiserror.workspace = true

[lints]
workspace = true
